# Generated by Django 4.0.4 on 2024-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_1',
            field=models.CharField(choices=[('sidou', '私道'), ('none', ' '), ('koudo', '公道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_2',
            field=models.CharField(choices=[('sidou', '私道'), ('none', ' '), ('koudo', '公道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_3',
            field=models.CharField(choices=[('sidou', '私道'), ('none', ' '), ('koudo', '公道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='外壁後退距離制限',
            field=models.CharField(choices=[('a', '1.5m以上'), ('none', ' '), ('b', '1m以上')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='幅員_maru10',
            field=models.CharField(choices=[('none', ' '), ('4', '4m'), ('6', '6m')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='指定番号_年号',
            field=models.CharField(choices=[('s', '昭和'), ('r', '令和'), ('h', '平成'), ('none', ' ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_1',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('u', 'ウ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ'), ('e', 'エ'), ('ki', 'キ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_2',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('u', 'ウ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ'), ('e', 'エ'), ('ki', 'キ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_3',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('u', 'ウ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ'), ('e', 'エ'), ('ki', 'キ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='絶対高さ制限',
            field=models.CharField(choices=[('YES2', '有(12m)'), ('NONE', ' '), ('NO', '無'), ('YES1', '有(10m)')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
