# Generated by Django 4.0.4 on 2024-05-02 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_land_m_公私道の別_1_alter_land_m_公私道の別_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_1',
            field=models.CharField(choices=[('koudo', '公道'), ('none', ' '), ('sidou', '私道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_2',
            field=models.CharField(choices=[('koudo', '公道'), ('none', ' '), ('sidou', '私道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='公私道の別_3',
            field=models.CharField(choices=[('koudo', '公道'), ('none', ' '), ('sidou', '私道')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='外壁後退距離制限',
            field=models.CharField(choices=[('none', ' '), ('a', '1.5m以上'), ('b', '1m以上')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='指定番号_年号',
            field=models.CharField(choices=[('s', '昭和'), ('r', '令和'), ('none', ' '), ('h', '平成')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_1',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('ki', 'キ'), ('u', 'ウ'), ('e', 'エ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_2',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('ki', 'キ'), ('u', 'ウ'), ('e', 'エ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='接道道路種類_3',
            field=models.CharField(choices=[('none', ' '), ('a', 'ア'), ('ki', 'キ'), ('u', 'ウ'), ('e', 'エ'), ('ka', 'カ'), ('o', 'オ'), ('i', 'イ')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='land_m',
            name='絶対高さ制限',
            field=models.CharField(choices=[('NONE', ' '), ('YES1', '有(10m)'), ('YES2', '有(12m)'), ('NO', '無')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(blank=True, choices=[('light', 'ライトプラン'), ('medium', 'ミディアムプラン'), ('premium', 'プレミアムプラン')], default='light', max_length=10),
        ),
    ]
